<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="CoreTests.fs" />
    <Compile Include="NetTests.fs" />
    <Compile Include="UiTests.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.FuncUI" Version="2.0.0" />
    <PackageReference Include="Avalonia.Headless" Version="12.1.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.0" />
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="FsCheck.Xunit" Version="3.3.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Pegasus.Core\Pegasus.Core.fsproj" />
    <ProjectReference Include="..\..\src\Pegasus.Net\Pegasus.Net.fsproj" />
    <ProjectReference Include="..\..\src\Pegasus.App\Pegasus.App.fsproj" />
  </ItemGroup>

</Project>